export const DEBUG_RENDERING_WORLD_AXIS = false;
export const DEBUG_RENDERING_ALL_TRIANGLES_CENTER = false;
export const DEBUG_RENDERING_TRIANGLES_CENTER_DURING_ROTATION = false;
export const DEBUG_RENDERING_ADJACENTS = false;
export const DEBUG_RENDERING_ROTATION_NODE_ALIGNMENT = false;
export const DEBUG_RENDERING_BONES_IDENTIFIER = false;
export const DEBUG_RENDERING_ADJS_TRIANGLES_BY_ID = false;
