# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
'on':
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
defaults:
  run:
   working-directory: xagon-react-app
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: "${{ matrix.node-version }}"
        cache: npm
        cache-dependency-path: xagon-react-app/package-lock.json
    - run: npm ci
    - run: npm run build --if-present   
    - name: Push to https://github.com/talex-tnt/talex-tnt.github.io
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: './xagon-react-app/xagon'
        target-directory: 'xagon-js'
        destination-github-username: 'talex-tnt'
        destination-repository-name: 'talex-tnt.github.io'
        user-email: alextinti83@gmail.com
        target-branch: master
